/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-03-11 02:09:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.template.demo_005f2.pages.charts;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chartjs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <!-- Required meta tags -->\n");
      out.write("    <meta charset=\"utf-8\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("    <title>Plus Admin</title>\n");
      out.write("    <!-- plugins:css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../../assets/vendors/mdi/css/materialdesignicons.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../../assets/vendors/flag-icon-css/css/flag-icon.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../../assets/vendors/css/vendor.bundle.base.css\">\n");
      out.write("    <!-- endinject -->\n");
      out.write("    <!-- Plugin css for this page -->\n");
      out.write("    <!-- End Plugin css for this page -->\n");
      out.write("    <!-- inject:css -->\n");
      out.write("    <!-- endinject -->\n");
      out.write("    <!-- Layout styles -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../../assets/css/demo_2/style.css\" />\n");
      out.write("    <!-- End layout styles -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../../../assets/images/favicon.png\" />\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <div class=\"container-scroller\">\n");
      out.write("      <!-- partial:../../partials/_horizontal-navbar.html -->\n");
      out.write("      <div class=\"horizontal-menu\">\n");
      out.write("        <nav class=\"navbar top-navbar col-lg-12 col-12 p-0\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <div class=\"text-center navbar-brand-wrapper d-flex align-items-center justify-content-center\">\n");
      out.write("              <a class=\"navbar-brand brand-logo\" href=\"../../index.jsp\">\n");
      out.write("                <img src=\"../../../assets/images/logo.svg\" alt=\"logo\" />\n");
      out.write("                <span class=\"font-12 d-block font-weight-light\">Responsive Dashboard </span>\n");
      out.write("              </a>\n");
      out.write("              <a class=\"navbar-brand brand-logo-mini\" href=\"../../index.jsp\"><img src=\"../../../assets/images/logo-mini.svg\" alt=\"logo\" /></a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"navbar-menu-wrapper d-flex align-items-center justify-content-end\">\n");
      out.write("              <ul class=\"navbar-nav mr-lg-2\">\n");
      out.write("                <li class=\"nav-item nav-search d-none d-lg-block\">\n");
      out.write("                  <div class=\"input-group\">\n");
      out.write("                    <div class=\"input-group-prepend hover-cursor\" id=\"navbar-search-icon\">\n");
      out.write("                      <span class=\"input-group-text\" id=\"search\">\n");
      out.write("                        <i class=\"mdi mdi-magnify\"></i>\n");
      out.write("                      </span>\n");
      out.write("                    </div>\n");
      out.write("                    <input type=\"text\" class=\"form-control\" id=\"navbar-search-input\" placeholder=\"Search\" aria-label=\"search\" aria-describedby=\"search\" />\n");
      out.write("                  </div>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("              <ul class=\"navbar-nav navbar-nav-right\">\n");
      out.write("                <li class=\"nav-item nav-profile dropdown\">\n");
      out.write("                  <a class=\"nav-link\" id=\"profileDropdown\" href=\"#\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("                    <div class=\"nav-profile-img\">\n");
      out.write("                      <img src=\"../../../assets/images/faces/face1.jpg\" alt=\"image\" />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"nav-profile-text\">\n");
      out.write("                      <p class=\"text-black font-weight-semibold m-0\"> Olson jass </p>\n");
      out.write("                      <span class=\"font-13 online-color\">online <i class=\"mdi mdi-chevron-down\"></i></span>\n");
      out.write("                    </div>\n");
      out.write("                  </a>\n");
      out.write("                  <div class=\"dropdown-menu navbar-dropdown\" aria-labelledby=\"profileDropdown\">\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                      <i class=\"mdi mdi-cached me-2 text-success\"></i> Activity Log </a>\n");
      out.write("                    <div class=\"dropdown-divider\"></div>\n");
      out.write("                    <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                      <i class=\"mdi mdi-logout me-2 text-primary\"></i> Signout </a>\n");
      out.write("                  </div>\n");
      out.write("                </li>\n");
      out.write("              </ul>\n");
      out.write("              <button class=\"navbar-toggler navbar-toggler-right d-lg-none align-self-center\" type=\"button\" data-toggle=\"horizontal-menu-toggle\">\n");
      out.write("                <span class=\"mdi mdi-menu\"></span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("        <nav class=\"bottom-navbar\">\n");
      out.write("          <div class=\"container\">\n");
      out.write("            <ul class=\"nav page-navigation\">\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"../../index.jsp\">\n");
      out.write("                  <i class=\"mdi mdi-compass-outline menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Dashboard</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a href=\"#\" class=\"nav-link\">\n");
      out.write("                  <i class=\"mdi mdi-monitor-dashboard menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">UI Elements</span>\n");
      out.write("                  <i class=\"menu-arrow\"></i>\n");
      out.write("                </a>\n");
      out.write("                <div class=\"submenu\">\n");
      out.write("                  <ul class=\"submenu-item\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                      <a class=\"nav-link\" href=\"../../pages/ui-features/buttons.jsp\">Buttons</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                      <a class=\"nav-link\" href=\"../../pages/ui-features/dropdowns.jsp\">Dropdown</a>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                      <a class=\"nav-link\" href=\"../../pages/ui-features/typography.jsp\">Typography</a>\n");
      out.write("                    </li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"../../pages/forms/basic_elements.jsp\">\n");
      out.write("                  <i class=\"mdi mdi-clipboard-text menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Forms</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"../../pages/icons/mdi.jsp\">\n");
      out.write("                  <i class=\"mdi mdi-contacts menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Icons</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"../../pages/charts/chartjs.jsp\">\n");
      out.write("                  <i class=\"mdi mdi-chart-bar menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Charts</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a class=\"nav-link\" href=\"../../pages/tables/basic-table.jsp\">\n");
      out.write("                  <i class=\"mdi mdi-table-large menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Tables</span>\n");
      out.write("                </a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <a href=\"https://www.bootstrapdash.com/demo/plus-free/documentation/documentation.html\" class=\"nav-link\" target=\"_blank\">\n");
      out.write("                  <i class=\"mdi mdi-file-document-box menu-icon\"></i>\n");
      out.write("                  <span class=\"menu-title\">Docs</span></a>\n");
      out.write("              </li>\n");
      out.write("              <li class=\"nav-item\">\n");
      out.write("                <div class=\"nav-link d-flex\">\n");
      out.write("                  <button class=\"btn btn-sm bg-danger text-white\"> Trailing </button>\n");
      out.write("                  <div class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link count-indicator dropdown-toggle text-white font-weight-semibold\" id=\"notificationDropdown\" href=\"#\" data-bs-toggle=\"dropdown\"> English </a>\n");
      out.write("                    <div class=\"dropdown-menu dropdown-menu-right navbar-dropdown preview-list\" aria-labelledby=\"notificationDropdown\">\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                        <i class=\"flag-icon flag-icon-bl me-3\"></i> French </a>\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                        <i class=\"flag-icon flag-icon-cn me-3\"></i> Chinese </a>\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                        <i class=\"flag-icon flag-icon-de me-3\"></i> German </a>\n");
      out.write("                      <div class=\"dropdown-divider\"></div>\n");
      out.write("                      <a class=\"dropdown-item\" href=\"#\">\n");
      out.write("                        <i class=\"flag-icon flag-icon-ru me-3\"></i>Russian </a>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <a class=\"text-white\" href=\"../../index.jsp\"><i class=\"mdi mdi-home-circle\"></i></a>\n");
      out.write("                </div>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("      </div>\n");
      out.write("      <!-- partial -->\n");
      out.write("      <div class=\"container-fluid page-body-wrapper\">\n");
      out.write("        <div class=\"main-panel\">\n");
      out.write("          <div class=\"content-wrapper\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("              <h3 class=\"page-title\">Chart-js</h3>\n");
      out.write("              <nav aria-label=\"breadcrumb\">\n");
      out.write("                <ol class=\"breadcrumb\">\n");
      out.write("                  <li class=\"breadcrumb-item\"><a href=\"#\">Charts</a></li>\n");
      out.write("                  <li class=\"breadcrumb-item active\" aria-current=\"page\"> Chart-js </li>\n");
      out.write("                </ol>\n");
      out.write("              </nav>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Line chart</h4>\n");
      out.write("                    <canvas id=\"lineChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Bar chart</h4>\n");
      out.write("                    <canvas id=\"barChart\" style=\"height: 230px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Area chart</h4>\n");
      out.write("                    <canvas id=\"areaChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Doughnut chart</h4>\n");
      out.write("                    <canvas id=\"doughnutChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Pie chart</h4>\n");
      out.write("                    <canvas id=\"pieChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"col-lg-6 grid-margin stretch-card\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                  <div class=\"card-body\">\n");
      out.write("                    <h4 class=\"card-title\">Scatter chart</h4>\n");
      out.write("                    <canvas id=\"scatterChart\" style=\"height: 250px;\"></canvas>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <!-- content-wrapper ends -->\n");
      out.write("          <!-- partial:../../partials/_footer.html -->\n");
      out.write("          <footer class=\"footer\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("              <div class=\"d-sm-flex justify-content-center justify-content-sm-between\">\n");
      out.write("                <span class=\"text-muted text-center text-sm-left d-block d-sm-inline-block\">Copyright © 2021 <a href=\"https://www.bootstrapdash.com/\" target=\"_blank\">BootstrapDash</a>. All rights reserved.</span>\n");
      out.write("                <span class=\"float-none float-sm-right d-block mt-1 mt-sm-0 text-center\">Hand-crafted & made with <i class=\"mdi mdi-heart text-danger\"></i></span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </footer>\n");
      out.write("          <!-- partial -->\n");
      out.write("        </div>\n");
      out.write("        <!-- main-panel ends -->\n");
      out.write("      </div>\n");
      out.write("      <!-- page-body-wrapper ends -->\n");
      out.write("    </div>\n");
      out.write("    <!-- container-scroller -->\n");
      out.write("    <!-- plugins:js -->\n");
      out.write("    <script src=\"../../../assets/vendors/js/vendor.bundle.base.js\"></script>\n");
      out.write("    <!-- endinject -->\n");
      out.write("    <!-- Plugin js for this page -->\n");
      out.write("    <script src=\"../../../assets/vendors/chart.js/Chart.min.js\"></script>\n");
      out.write("    <!-- End plugin js for this page -->\n");
      out.write("    <!-- inject:js -->\n");
      out.write("    <script src=\"../../../assets/js/off-canvas.js\"></script>\n");
      out.write("    <script src=\"../../../assets/js/hoverable-collapse.js\"></script>\n");
      out.write("    <script src=\"../../../assets/js/misc.js\"></script>\n");
      out.write("    <script src=\"../../../assets/js/settings.js\"></script>\n");
      out.write("    <script src=\"../../../assets/js/todolist.js\"></script>\n");
      out.write("    <!-- endinject -->\n");
      out.write("    <!-- Custom js for this page -->\n");
      out.write("    <script src=\"../../../assets/js/chart.js\"></script>\n");
      out.write("    <!-- End custom js for this page -->\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
